### PR TITLE
Delete button

### PR DESCRIPTION
**Pull request by ygeyzel**

### CODE REVIEW

**Comment by guysoft** [comment]
Cool!
Two notes:
1. Its worth adding a yes/no dialog asking "are you sure you want to delete backup x"?
2. Worth noting that Edit button is enabled, but not implementing yet

**Comment by ygeyzel** [comment]
> Cool!
> Two notes:
> 
> 1. Its worth adding a yes/no dialog asking "are you sure you want to delete backup x"?
> 2. Worth noting that Edit button is enabled, but not implementing yet

Ok, I'll add the dialog and disable Edit button.

**Comment by guysoft** [comment]
Ok looks good, will pull and test, then merge.

**Comment by guysoft** [comment]
Tested, works!

**Pull request merged**
