### PR TITLE
Add job button

### PR DESCRIPTION
**Pull request by ygeyzel**

### CODE REVIEW

**Comment by guysoft** [comment]
Looks cool! Also using puv/sub. Did you get that from some guide?
Was it tested and safe to pull?

**Comment by ygeyzel** [comment]
> Looks cool! Also using puv/sub. Did you get that from some guide?

I tried to  get 2 things:
1. Avoid code duplication by using same functions for reading jobs at init and adding new jobs.
2. Allow adding jobs only at Main Invisible Window and then notify other relevant components (MainFrame in this case).

The problem was that in one flow (adding new jobs) we need to notify the Main Frame while in the other (init) it's not exist yet, I've tried to find a way to do it with wxWidgets events but I got to conclusion that pub/sub mechanism would be much cleaner and maintainable solution.

> Was it tested and safe to pull?

I checked that you can add jobs and that they are saved and uploaded at next runs, I haven't done any E/E tests.

**Comment by guysoft** [comment]
Ok tested here too and it works.

The next task is to add the edit button. Its grayed out so it would need to be enabled when you select a job from the menu. I can open it as an issue here if you like.

**Comment by ygeyzel** [comment]
> Ok tested here too and it works.
> 
> The next task is to add the edit button. Its grayed out so it would need to be enabled when you select a job from the menu. I can open it as an issue here if you like.

Ok, open it as an issue

**Comment by guysoft** [comment]
See #4 
I need to add more stuff there but that is a decent job already

**Pull request merged**
