### PR TITLE
Edit job button

### PR DESCRIPTION
**Pull request by ygeyzel**

### CODE REVIEW

**Comment by guysoft** [comment]
Looks good - did you test it?
* Update* - seems to load and save correctly.

**Comment by guysoft** [comment]
Tested here, seems to work.

**Comment by guysoft** [comment]
``def update_backup`` Does not handle rename correctly.
If you rename a job, its data folder still stays under the previous name.

It should:
1. check if the name does not already exist
2. move the data folder to the new name.

**Comment by ygeyzel** [comment]
> `def update_backup` Does not handle rename correctly.
> If you rename a job, its data folder still stays under the previous name.
> 
> It should:
> 
> 1. check if the name does not already exist
> 2. move the data folder to the new name.

Ok, I'll fix that

**Comment by guysoft** [comment]
Do you think you will get to this sometime?
I am staring to close other MVP issues and not sure if to wait for you to complete this or to do it myself.

I need to add a new field for the "server url", and it would make more sense to merge this before adding that.

**Comment by ygeyzel** [comment]
> Do you think you will get to this sometime?
> I am staring to close other MVP issues and not sure if to wait for you to complete this or to do it myself.
> 
> I need to add a new field for the "server url", and it would make more sense to merge this before adding that.

I'll work on this on this weekend

**Comment by guysoft** [comment]
Cool! One validation that is missing, is if a backup with that name already exists

**Comment by guysoft** [comment]
Merging because usable, it would make more sense tough to have a physical message dialog alerting the user what the problem is, rather than raising an exception.

**Pull request merged**
